# Generated by Django 5.1.6 on 2025-05-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('fallback_color', models.CharField(default='#000000', max_length=7)),
                ('width', models.FloatField(default=3.0)),
                ('height', models.FloatField(default=4.0)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=3)),
                ('position_z', models.FloatField(default=0)),
                ('rotation_y', models.FloatField(default=0)),
            ],
        ),
    ]
